name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
      release_name:
        description: 'version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zip rar

      - name: Prepare release bundle
        run: |
          NAME="zapret2-discord-youtube-strats"

          mkdir "$NAME"

          cp -r bin "$NAME/"
          cp -r lists "$NAME/"
          cp -r lua "$NAME/"
          cp -r utils "$NAME/"
          cp *.bat "$NAME/"

      - name: Create archives
        run: |
          NAME="zapret2-discord-youtube-strats"

          zip -qr "${NAME}.zip" "$NAME"
          rar a -idq "${NAME}.rar" "$NAME"
        # tar --owner=0 --group=0 -czf "${NAME}.tar.gz" "$NAME"

      - name: Print SHA256 checksums
        run: |
          NAME="zapret2-discord-youtube-strats"

          sha256sum \
            "${NAME}.zip" \
            "${NAME}.rar"
        # "${NAME}.tar.gz"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.release_name }}
          files: |
            zapret2-discord-youtube-strats.zip
            zapret2-discord-youtube-strats.rar
        # zapret-discord-youtube-strats.tar.gz